backend:
  name: github
  repo: Derss13/capirava-site
  branch: main

media_folder: "imagens/uploads"
public_folder: "/imagens/uploads"

collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - file: "content/sobre.md"
        label: "Sobre"
        name: "sobre"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "markdown" }
